receivers:
  opencensus:
    endpoint: 0.0.0.0:55678
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:54317
      http:
        endpoint: 0.0.0.0:55681
        cors_allowed_origins: [${RECEIVERS_CORS_ALLOWED_ORIGINS}]

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 2000
  batch:

extensions:
  health_check:
  pprof:
    endpoint: :1888
  zpages:
    endpoint: :55679

exporters:
  logging:
    loglevel: debug
  prometheus:
    endpoint: "0.0.0.0:8889"
    namespace: otelcollector
  zipkin:
    endpoint: "${ZIPKIN_ENDPOINT}"
    format: proto
  jaeger:
    endpoint: "${JAEGER_ENDPOINT}"
    insecure: true
  otlp/elastic:
    # Elastic APM server https endpoint without the "https://" prefix
    endpoint: "${ELASTIC_APM_SERVER_ENDPOINT}"
    insecure: "${ELASTIC_APM_SERVER_ENDPOINT_INSECURE}"
    headers:
      # Elastic APM Server secret token
      Authorization: "Bearer ${ELASTIC_APM_SERVER_TOKEN}"
  datadog/api:
    env: ${DATADOG_ENV}
    tags: [${DATADOG_TAGS}]
    api:
      key: ${DATADOG_API_KEY}

  #otlp:
  #  endpoint: "tempo:55680"
  #  insecure: true
  #  headers:
  #    x-scope-orgid: foo-bar-baz

service:
  extensions: [pprof, zpages, health_check]
  pipelines:
    traces:
      receivers: [${TRACES_RECEIVERS_ENABLED}]
      processors: [batch]
      exporters: [${TRACES_EXPORTERS_ENABLED}]
    metrics:
      receivers: [${METRICS_RECEIVERS_ENABLED}]
      processors: [batch]
      exporters: [${METRICS_EXPORTERS_ENABLED}]
    logs:
      receivers: [${LOGS_RECEIVERS_ENABLED}]
      processors: [batch]
      exporters: [${LOGS_EXPORTERS_ENABLED}]
