app_name: "product-service"
server_port: 9090
db_name: "dev"
db_user_ddl: "postgres"
db_pass_ddl: "s3cr3tp4ssw0rd"
db_user_dml: "postgres"
db_pass_dml: "s3cr3tp4ssw0rd"
db_server: "localhost"
db_port: "5432"
db_migration_table: "product_service_migrations"
db_migration_path: "../../../db/migrations"
db_pool_max_open_conns: "2"
db_pool_max_idle_conns: "2"
db_pool_conn_max_lifetime: "1h"
