server:
  port: 8080

spring:
  application:
    name: order-service
  jackson:
    serialization:
      indent_output: true
      write_dates_as_timestamps: false
      write_durations_as_timestamps: false
  flyway:
    enabled: true
    locations: classpath:db/migration/postgres
    url: jdbc:postgresql://${DB_SERVER}:${DB_SERVER_PORT}/${DB_NAME}
    user: ${DB_USER}
    password: ${DB_PASS}
    baseline-version: 8
    baseline-on-migrate: true
  datasource:
    url: jdbc:postgresql://${DB_SERVER}:${DB_SERVER_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASS}
    platform: "postgres"
    driverClassName: org.postgresql.Driver
    hikari:
      connectionTestQuery: SELECT 1
      minIdle: 1
      maxPoolSize: ${DB_MAX_POOL_SIZE}
      poolName: pool
  jpa:
    database: "POSTGRESQL"
    hibernate:
      show_sql: true
      format_sql: true
      ddl-auto: "validate"
      dialect: "org.hibernate.dialect.PostgreSQL94Dialect"
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
  jmx:
    enabled: "true"
    default-domain: "com.amaxson.order"

management:
  endpoint:
    health:
      show-details: "ALWAYS"
    shutdown:
      enabled: true
  endpoints:
    web:
      #base-path: "/monitoring"
      exposure:
        include: "info,health,loggers,httptrace,metric,prometheus"
  metrics:
    export:
      simple:
        enabled: "true"
        step: "30s"
        mode: "STEP"
      prometheus:
        enabled: "true"

endpoints:
  shutdown:
    enabled: true

logging.pattern.console: "%d{yyyy-MM-dd HH:mm:ss} - %logger{36} - %msg t:%X{traceId} s:%X{spanId} %n"
