global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: 'collector'
    metrics_path: /metrics
    scrape_interval: 10s
    static_configs:
      - targets: ['collector:8889']
      - targets: ['collector:8888']
